id: AB358F734
title: Prayer for this Life, the Next and the Bardos
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:23:09.828868
  last_modified_at: 2022-03-01 00:23:09.828871
