id: AB358F734
title: Prayer to Pema Tötreng Tsal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:23:09.832282
  last_modified_at: 2022-03-01 00:23:09.832287
