id: AB358F734
title: Brief Succession of Lives Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:23:09.825231
  last_modified_at: 2022-03-01 00:23:09.825233
