id: AB358F734
title: Prayer to Khenpo Ngawang Palzang
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:23:09.830046
  last_modified_at: 2022-03-01 00:23:09.830049
