id: AB358F734
title: 'Gyang Lu: A Song of Calling from Afar'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:23:09.827354
  last_modified_at: 2022-03-01 00:23:09.827357
