id: AB358F734
title: Brief Homage to the Twenty-One Tārās
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:23:09.823442
  last_modified_at: 2022-03-01 00:23:09.823451
